'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const repositoryRoot = path.resolve(__dirname, '..', '..', '..');

function readPackage(directory) {
    return JSON.parse(fs.readFileSync(path.join(repositoryRoot, directory, 'package.json'), 'utf8'));
}

test('the test harness runs on the supported Node 24 LTS line', () => {
    assert.equal(Number.parseInt(process.versions.node, 10), 24);
    assert.equal(fs.readFileSync(path.join(repositoryRoot, '.nvmrc'), 'utf8').trim(), '24.20.0');
    assert.equal(readPackage('server').engines.node, '>=24.0.0 <25');
    assert.equal(readPackage('client').engines.node, '>=24.0.0 <25');
});

test('obsolete native and browser test components are absent', () => {
    const serverPackage = readPackage('server');
    const clientPackage = readPackage('client');

    assert.equal(serverPackage.devDependencies['phantomjs-prebuilt'], undefined);
    assert.equal(serverPackage.devDependencies['selenium-webdriver'], undefined);
    assert.equal(clientPackage.devDependencies['node-sass'], undefined);
    assert.ok(clientPackage.devDependencies.sass, 'Dart Sass must replace node-sass');
});

test('lockfiles use a modern deterministic npm format', () => {
    for (const directory of ['server', 'client']) {
        const lock = JSON.parse(fs.readFileSync(path.join(repositoryRoot, directory, 'package-lock.json'), 'utf8'));
        assert.ok(lock.lockfileVersion >= 3, `${directory} lockfile must be regenerated by the Node 24 npm toolchain`);
        assert.ok(lock.packages, `${directory} lockfile must include package metadata`);
    }
});
